[admin]
users = [
  {username = "priya2002", password = "12345"},
  {username = "ankur2002", password = "12345"},
  {username = "sumit2002", password = "12345"},
  {username = "mantu2002", password = "12345"},
  {username = "madan2002", password = "12345"},
  {username = "mayank2002", password = "12345"}
]

[smtp]
username = "cincout000@gmail.com"
password = "gxpq kvds mijl dryj"
